
CREATE TABLE MEMBRE (
	EMAIL VARCHAR(30) NOT NULL, 
	MDP VARCHAR(30) NOT NULL,
	NOM VARCHAR(30) NOT NULL, 
	PRENOM VARCHAR(20) NOT NULL,
	VILLE VARCHAR(30), 
	AGE NUMERIC(3,0),
	NUMTEL VARCHAR(9),
	AVIS NUMERIC(6, 0),
	BANNI BOOLEAN DEFAULT NULL,
	PRIMARY KEY (MAIL)
);

CREATE TABLE VOITURE (
	ID_V NUMERIC(6,0),
	MARQUE VARCHAR(20),
	NOM_V VARCHAR(30),
	TYPE VARCHAR(30),
	COULEUR VARCHAR(20),

	PRIMARY KEY (ID_V)
);

CREATE TABLE VOITURE_MEMBRE (
	ID_VM NUMERIC(6, 0),
	MAIL_MEM VARCHAR(30),
	ID_VOIT NUMERIC(6, 0),

	PRIMARY KEY (ID_VM),
	FOREIGN KEY (MAIL_MEM) REFERENCES MEMBRE(MAIL),
	FOREIGN KEY (ID_VOIT) REFERENCES VOITURE(ID_V)
);

CREATE TABLE TRAJET (
	ID_T NUMERIC(6, 0),
	MAIL_MEMBRE VARCHAR(30),
	VILLE_DEP VARCHAR(30),
	DATE_RDV DATE,	
	ADR_RDV VARCHAR(30),
	VILLE_AR VARCHAR(30),
	ADR_AR VARCHAR(30),
	TYPE_VOIT VARCHAR(30),
	NB_PLACES NUMERIC(6, 0),
	PRIX NUMERIC(6, 0),

	PRIMARY KEY (ID_T),
	FOREIGN KEY (MAIL_MEMBRE) REFERENCES MEMBRE(MAIL)
);

CREATE TABLE DEMANDE_TRAJET (
	ID_D NUMERIC(6, 0),
	MAIL_DEM VARCHAR(30),
	ID_TRAJET NUMERIC(6, 0),

	PRIMARY KEY (ID_D),
	FOREIGN KEY (MAIL_DEM) REFERENCES MEMBRE(MAIL),
	FOREIGN KEY (ID_TRAJET) REFERENCES TRAJET(ID_T)
);

