CREATE TABLE MEMBRE (
	MAIL VARCHAR(30),  
	NOM VARCHAR(30)  CONSTRAINT MEMNOM NOT NULL, 
	PRENOM VARCHAR(20),
	VILLE VARCHAR(30), 
	AGE NUMERIC(3,0),
	NUMTEL VARCHAR(9),
	AVIS NUMERIC(6, 0),
	CONSTRAINT DOM_NBVOIT CHECK (NBVOIT BETWEEN 0 AND 10)
);

CREATE TABLE VOITURE (
	ID NUMERIC(6,0),
	MARQUE VARCHAR(20),
	NOM VARCHAR(30),
	TYPE VARCHAR(30),
	COULEUR VARCHAR(20)
);

CREATE TABLE VOITURE_MEMBRE (
	ID NUMERIC(6, 0),
	MAIL_MEM VARCHAR(30),
	VOIT_ID NUMERIC(6, 0)
);

CREATE TABLE TRAJET (
	ID NUMERIC(6, 0),
	MAIL_MEM VARCHAR(30),
	VILLE_DEP VARCHAR(30),
	DATE_RDV DATE,	
	ADR_RDV VARCHAR(30),
	VILLE_AR VARCHAR(30),
	ADR_AR VARCHAR(30),
	TYPE_VOIT VARCHAR(30),
	NB_PLACES NUMERIC(6, 0),
	PRIX NUMERIC(6, 0)
);

CREATE TABLE DEMANDE_TRAJET (
	ID NUMERIC(6, 0),
	DEMANDEUR_MAIL VARCHAR(30),
	TRAJET_ID NUMERIC(6, 0),
);