/*
DROP TABLE IF EXISTS MEMBRE;
DROP TABLE IF EXISTS VOITURE;
DROP TABLE IF EXISTS VOITURE_MEMBRE;
DROP TABLE IF EXISTS TRAJET;
DROP TABLE IF EXISTS DEMANDE_TRAJET;
*/
CREATE TABLE MEMBRE (
	MAIL VARCHAR(30) NOT NULL,  
	NOM VARCHAR(30) NOT NULL, 
	PRENOM VARCHAR(20),
	VILLE VARCHAR(30), 
	AGE NUMERIC(3,0),
	NUMTEL VARCHAR(9),
	AVIS NUMERIC(6, 0),

	PRIMARY KEY (MAIL)
);

CREATE TABLE VOITURE (
	IDV NUMERIC(6,0),
	MARQUE VARCHAR(20),
	NOM VARCHAR(30),
	TYPE VARCHAR(30),
	COULEUR VARCHAR(20),

	PRIMARY KEY (IDV)
);

CREATE TABLE VOITURE_MEMBRE (
	IDVM NUMERIC(6, 0),
	MAIL_MEM VARCHAR(30),
	ID_VOIT NUMERIC(6, 0),

	PRIMARY KEY (IDVM),
	FOREIGN KEY (MAIL_MEM) REFERENCES MEMBRE(MAIL),
	FOREIGN KEY (ID_VOIT) REFERENCES VOITURE(IDV)
);

CREATE TABLE TRAJET (
	IDT NUMERIC(6, 0),
	MAIL_MEM VARCHAR(30),
	VILLE_DEP VARCHAR(30),
	DATE_RDV DATE,	
	ADR_RDV VARCHAR(30),
	VILLE_AR VARCHAR(30),
	ADR_AR VARCHAR(30),
	TYPE_VOIT VARCHAR(30),
	NB_PLACES NUMERIC(6, 0),
	PRIX NUMERIC(6, 0),

	PRIMARY KEY (IDT),
	FOREIGN KEY (MAIL_MEM) REFERENCES MEMBRE(MAIL)
);

CREATE TABLE DEMANDE_TRAJET (
	IDD NUMERIC(6, 0),
	MAIL_DEM VARCHAR(30),
	ID_TRAJET NUMERIC(6, 0),

	PRIMARY KEY (IDD),
	FOREIGN KEY (MAIL_DEM) REFERENCES MEMBRE(MAIL),
	FOREIGN KEY (ID_TRAJET) REFERENCES TRAJET(IDT)
);

