//Q1:

SELECT NOM, PRENOM FROM ABONNE WHERE VILLE = 'MONTPELLIER'

//Q2:
SELECT * FROM EXEMPLAIRE WHERE CODE_PRET = 'EMPRUNTABLE'

//Q3:

SELECT TITRE, CATEGORIE FROM LIVRE WHERE CATEGORIE NOT IN
(SELECT TITRE, CATEGORIE FROM LIVRE WHERE CATEGORIE = 'LOISIRS'
       	      		     	   OR CATEGORIE = 'SCIENCES'
				   OR CATEGORIE = 'MEDECINE')

//Q4:

SELECT * FROM EMPRUNT WHERE D_RET_REEL IS NULL

//Q5:
